const imagesName = [
  "alfajor.png",
  "alien.png",
  "asteroid.png",
  "astronaut.png",
  "bear (1).png",
  "bear.png",
  "bird (1).png",
  "bird.png",
  "camel.png",
  "character.png",
  "crossbill.png",
  "earth.png",
  "falcon.png",
  "gazelle.png",
  "goat.png",
  "heron.png",
  "hitotsume-kozo.png",
  "kingfisher.png",
  "koala (1).png",
  "koala.png",
  "meteorite.png",
  "monster.png",
  "nekomata.png",
  "oni.png",
  "owl.png",
  "panda.png",
  "parrot.png",
  "patty.png",
  "pelican.png",
  "planets (1).png",
  "planets.png",
  "rhinoceros.png",
  "rocket.png",
  "satellite.png",
  "saturn.png",
  "shooting-star.png",
  "space-shuttle.png",
  "spell.png",
  "sun.png",
  "ufo (1).png",
  "ufo (2).png",
  "ufo.png",
  "unicorn.png",
];

export default imagesName;
